/**
 * Core Pattern Library with Pre-computed Embeddings
 *
 * This file is auto-generated by scripts/buildPatterns.ts
 * DO NOT EDIT MANUALLY - edit src/patterns/comprehensive-library.json instead
 *
 * Storage strategy:
 * - Patterns are bundled directly into Brainy for zero-latency access
 * - Embeddings are pre-computed and stored as binary Float32Array
 * - Total size: ~140KB (negligible for a neural library)
 * - No external files needed, works in all environments
 */
import type { Pattern } from './patternLibrary.js';
export declare const CORE_PATTERNS: Pattern[];
export declare const PATTERN_EMBEDDINGS_BINARY: Uint8Array | null;
export declare function getPatternEmbeddings(): Map<string, Float32Array>;
export declare const PATTERNS_VERSION = "2.0.0";
export declare const PATTERNS_METADATA: {
    totalPatterns: number;
    categories: string[];
    embeddingDimensions: number;
    storageSize: {
        patterns: string;
        embeddings: string;
        total: string;
    };
};
